export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const CLEAR_MOVIE = "CLEAR_MOVIE";
export const GET_RECOMMENDED_MOVIES_SUCCESS = "GET_RECOMMENDED_MOVIES_SUCCESS";
export const GET_CREDITS_SUCCESS = "GET_CREDITS_SUCCESS";